version: 0.0
os: ubuntu-18.04
files:
  - source: /
    destination: /home/ubuntu/app
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh

  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/application_start.sh
    
      timeout: 300
