#!/bin/sh
ssh ubuntu@3.36.100.222<<EOF
    
    sudo su
    pwd


    
    git pull origin main
    curl -o-   https://raw.githubusercontent.com/creationix/nvm/v0.33.8/install.sh    | bash
    npx prisma migrate generate
    exit
EOF

    #. ~/.nvm/nvm.sh 
    #nvm install 16.3.0	
    #npm install
    #npm install -g pm2
    #pm2 restart app.js